# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170222_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date started'),
            preserve_default=False,
        ),
    ]
