# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170228_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='date ended'),
        ),
    ]
