# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170228_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Testville', max_length=200)),
                ('state', models.CharField(default='Montigania', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='next_paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.Newspaper'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='prev_paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.Newspaper'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'state')]),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Location'),
        ),
    ]
