# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170306_2346'),
        ('news', '0006_auto_20170307_0616'),
    ]

    operations = [
    ]
