# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_merge_20170427_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='frequency',
            field=models.CharField(choices=[('WK', 'weekly'), ('MN', 'monthly'), ('OT', 'other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='news.Article'),
        ),
    ]
