# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170512_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
