# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170518_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date ended')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='key',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='editor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='New York', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='New York', max_length=200),
        ),
    ]
