# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170530_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='date_started',
            field=models.DateField(verbose_name='date started'),
        ),
    ]
