# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20170531_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='date_started',
            field=models.DateField(blank=True, verbose_name='date started'),
        ),
    ]
