# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newspaper_corpus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('issue__date__year',)},
        ),
    ]
