# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170605_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('issue__date',)},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('date_published',)},
        ),
    ]
