# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_auto_20170605_1508'),
        ('news', '0015_auto_20170605_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='topics',
            field=models.ManyToManyField(through='topics.YearTopicRank', to='topics.Topic'),
        ),
    ]
