# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20170607_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=40.7128, max_digits=7),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=-74.0059, max_digits=7),
        ),
    ]
