# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20170630_2053'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE news_article MODIFY title VARCHAR(500) CHARSET '
                + 'utf8mb4 COLLATE utf8mb4_unicode_ci'
            ],
            reverse_sql=[
                'ALTER TABLE news_article MODIFY title VARCHAR(500)'
            ]
        )
    ]
