# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20170630_2053'),
    ]

    operations = [
    ]
