# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_switch_to_utf8mb4_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['key'], name='news_articl_key_55a744_idx'),
        ),
    ]
