# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletopicrank',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterModelOptions(
            name='wordtopicrank',
            options={'ordering': ('rank',)},
        ),
    ]
