# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170518_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopicrank',
            name='score',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
