# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170518_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='key',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
