# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
