# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170530_1509'),
        ('topics', '0007_topic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Corpus'),
        ),
    ]
