# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_topic_corpus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('score',)},
        ),
    ]
