# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20170531_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletopicrank',
            options={'ordering': ('-score',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-score',)},
        ),
        migrations.AlterModelOptions(
            name='wordtopicrank',
            options={'ordering': ('-score',)},
        ),
    ]
