# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_auto_20170531_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTopicRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=10, max_digits=10)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
            options={
                'ordering': ('year', 'score'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='yeartopicrank',
            unique_together=set([('year', 'topic')]),
        ),
    ]
