# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_auto_20170605_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeartopicrank',
            name='corpus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Corpus'),
            preserve_default=False,
        ),
    ]
