# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_auto_20170606_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='articles',
            field=models.ManyToManyField(related_name='atr', through='topics.ArticleTopicRank', to='news.Article'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='words',
            field=models.ManyToManyField(related_name='wtr', through='topics.WordTopicRank', to='topics.Word'),
        ),
    ]
