# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0016_auto_20170627_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletopicrank',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='topic',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='wordtopicrank',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='yeartopicrank',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
