# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_auto_20170630_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletopicrank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='wordtopicrank',
            name='rank',
        ),
    ]
