# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0018_auto_20170630_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterModelOptions(
            name='yeartopicrank',
            options={'ordering': ('year', 'rank')},
        ),
    ]
