# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0019_auto_20170630_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-score',)},
        ),
        migrations.AlterModelOptions(
            name='yeartopicrank',
            options={'ordering': ('year', '-score')},
        ),
    ]
