# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0022_auto_20170718_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordtopicrank',
            options={},
        ),
    ]
