# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_auto_20180515_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletopicrank',
            options={},
        ),
    ]
