# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0026_auto_20180516_1354'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='topics_topi_key_a8262b_idx',
        ),
        migrations.AddIndex(
            model_name='wordtopicrank',
            index=models.Index(fields=['word'], name='topics_word_word_id_b42c64_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtopicrank',
            index=models.Index(fields=['topic'], name='topics_word_topic_i_97061b_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-score'], name='topics_topi_score_44d95d_idx'),
        ),
        migrations.AddIndex(
            model_name='yeartopicrank',
            index=models.Index(fields=['topic'], name='topics_year_topic_i_2d8ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='yeartopicrank',
            index=models.Index(fields=['year'], name='topics_year_year_242e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='yeartopicrank',
            index=models.Index(fields=['year', '-score'], name='topics_year_year_d76952_idx'),
        ),
    ]
