# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0028_auto_20180521_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtopicrank',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
