# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0029_wordtopicrank_rank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articletopicrank',
            index=models.Index(fields=['topic', '-score'], name='topics_arti_topic_i_bff8e2_idx'),
        ),
    ]
