# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0030_auto_20180522_1737'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wordtopicrank',
            name='topics_word_score_69579f_idx',
        ),
        migrations.AddIndex(
            model_name='wordtopicrank',
            index=models.Index(fields=['topic', 'rank'], name='topics_word_topic_i_52b50d_idx'),
        ),
    ]
