# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0035_auto_20180529_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeartopicrank',
            name='article_count',
            field=models.IntegerField(default=-1),
        ),
    ]
