# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0036_yeartopicrank_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeartopicrank',
            name='percentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
    ]
